In [1]:
import numpy as np

In [2]:
MyArray1=np.arange(1,20)
MyArray1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
range(1,10,2)

range(1, 10, 2)

In [4]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [5]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [6]:
list(range(1,12,2))

[1, 3, 5, 7, 9, 11]

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
MyArray2=np.array([1,2,3,4,3,5])
MyArray2

array([1, 2, 3, 4, 3, 5])

In [9]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

In [10]:
MyArray3=np.zeros((5,5))
MyArray3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
MyArray4=np.ones((5,5))
MyArray4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [13]:
rand=np.random.RandomState(30)
MyArray5=rand.randint(0,100,[3,5])
MyArray5

array([[37, 37, 45, 45, 12],
       [23,  2, 53, 17, 46],
       [ 3, 41,  7, 65, 49]])

In [14]:
MyArray5=rand.randint(0,100,[3,5])
MyArray5

array([[45, 61, 35, 18, 18],
       [76, 16,  6, 62, 27],
       [46, 45, 64, 62, 11]])

In [15]:
rand=np.random.RandomState(30)
MyArray5=rand.randint(0,100,[3,5])
MyArray5

array([[37, 37, 45, 45, 12],
       [23,  2, 53, 17, 46],
       [ 3, 41,  7, 65, 49]])

In [16]:
#36.2主要特征

In [17]:
MyArray4=np.zeros(shape=(2,15),dtype=np.int)
MyArray4

C:\Users\ALVINA~1\AppData\Local\Temp/ipykernel_38372/866771542.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  MyArray4=np.zeros(shape=(2,15),dtype=np.int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
import numpy as np
MyArray4=np.zeros(shape=(2,15),dtype=np.int)
MyArray4

C:\Users\ALVINA~1\AppData\Local\Temp/ipykernel_38372/3057969093.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  MyArray4=np.zeros(shape=(2,15),dtype=np.int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones([3,5],dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
#36.3切片与读取

In [22]:
import numpy as np
myArray=np.array(range(1,10))
myArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
myArray=np.arange(1,10)

In [24]:
myArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
myArray[0]

1

In [26]:
myArray[-1]

9

In [27]:
import numpy as np
myArray=np.array(range(0,10))
print("myArray=",myArray)
print("myArray[1:9:2]=",myArray[1:9:2])
print("myArray[:9:2]=",myArray[:9:2])

print("myArray[::2]=",myArray[::2])
print("myArray[::]=",myArray[::])
print("myArray[:8:]=",myArray[:8:])
print("myArray[:8]=",myArray[0:8])
print("myArray[4::]=",myArray[4::])
print("myArray[9:1:-2]=",myArray[9:1:-2])
print("myArray[::-2]",myArray[::-2])
print("myArray[[2,5,6]]=",myArray[[2,5,6]])
print("myArray[myArray>5]=",myArray[myArray>5])

myArray= [0 1 2 3 4 5 6 7 8 9]
myArray[1:9:2]= [1 3 5 7]
myArray[:9:2]= [0 2 4 6 8]
myArray[::2]= [0 2 4 6 8]
myArray[::]= [0 1 2 3 4 5 6 7 8 9]
myArray[:8:]= [0 1 2 3 4 5 6 7]
myArray[:8]= [0 1 2 3 4 5 6 7]
myArray[4::]= [4 5 6 7 8 9]
myArray[9:1:-2]= [9 7 5 3]
myArray[::-2] [9 7 5 3 1]
myArray[[2,5,6]]= [2 5 6]
myArray[myArray>5]= [6 7 8 9]


In [28]:
myArray[0:2]

array([0, 1])

In [29]:
myArray[1:5:2]

array([1, 3])

In [30]:
myArray[::2]

array([0, 2, 4, 6, 8])

In [31]:
myArray[::-2]

array([9, 7, 5, 3, 1])

In [32]:
myArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
myArray=np.array(range(1,11))
myArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
myArray[1,3,6]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [35]:
myArray[[1,3,6]]

array([2, 4, 7])

In [36]:
myArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
myArray[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [39]:
myArray[:,np.newaxis].shape

(10, 1)

In [40]:
myArray2=np.arange(1,21).reshape([5,4])
myArray2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [41]:
myArray2[[2,4],3]

array([12, 20])

In [43]:
x=[2,4]
myArray2[x,3]

array([12, 20])

In [44]:
#3.64浅拷贝与深拷贝

In [45]:
import numpy as np
myArray1=np.array(range(0,10))
myArray2=myArray1
myArray2[1]=100
myArray1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [46]:
import numpy as np
myArray1=np.array(range(0,10))
myArray2=myArray1.copy()
myArray2[1]=100
myArray1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
#36.5形状与重构

In [48]:
import numpy as np
MyArray5=np.arange(1,21)
MyArray5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
MyArray5.shape

(20,)

In [51]:
MyArray6=MyArray5.reshape(4,5)
MyArray6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
MyArray5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
MyArray5.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [54]:
MyArray5.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [55]:
MyArray5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
MyArray5.resize(4,5)
MyArray5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
MyArray5.swapaxes(0,1)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [58]:
MyArray5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
MyArray5=MyArray5.swapaxes(0,1)
MyArray5

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [60]:
MyArray5.flatten()

array([ 1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,  9, 14, 19,  5,
       10, 15, 20])

In [61]:
MyArray5

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [62]:
MyArray5.tolist()

[[1, 6, 11, 16],
 [2, 7, 12, 17],
 [3, 8, 13, 18],
 [4, 9, 14, 19],
 [5, 10, 15, 20]]

In [63]:
MyArray5.astype(np.float)

C:\Users\ALVINA~1\AppData\Local\Temp/ipykernel_38372/696771290.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  MyArray5.astype(np.float)


array([[ 1.,  6., 11., 16.],
       [ 2.,  7., 12., 17.],
       [ 3.,  8., 13., 18.],
       [ 4.,  9., 14., 19.],
       [ 5., 10., 15., 20.]])

In [64]:
MyArray5

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [66]:
#36.6属性计算

In [67]:
np.rank(MyArray5)

AttributeError: module 'numpy' has no attribute 'rank'

In [68]:
np.ndim(MyArray5)

2

In [69]:
MyArray5.ndim

2

In [70]:
np.shape(MyArray5)

(5, 4)

In [71]:
MyArray5.shape

(5, 4)

In [72]:
MyArray5.size

20

In [73]:
type(MyArray5)

numpy.ndarray

In [74]:
#36.6ndarray的计算

In [75]:
MyArray5*10

array([[ 10,  60, 110, 160],
       [ 20,  70, 120, 170],
       [ 30,  80, 130, 180],
       [ 40,  90, 140, 190],
       [ 50, 100, 150, 200]])

In [76]:
x=np.array([11,12,13,14,15,16,17,18])
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[11 12 13] [14 15] [16 17 18]


In [78]:
upper,lower=np.vsplit(MyArray5.reshape(4,5),[2])
print("上半部分为\n",upper)
print("\n\n下半部分为\n",lower)


上半部分为
 [[ 1  6 11 16  2]
 [ 7 12 17  3  8]]


下半部分为
 [[13 18  4  9 14]
 [19  5 10 15 20]]


In [79]:
np.concatenate((lower,upper),axis=0)

array([[13, 18,  4,  9, 14],
       [19,  5, 10, 15, 20],
       [ 1,  6, 11, 16,  2],
       [ 7, 12, 17,  3,  8]])

In [80]:
np.vstack([upper,lower])

array([[ 1,  6, 11, 16,  2],
       [ 7, 12, 17,  3,  8],
       [13, 18,  4,  9, 14],
       [19,  5, 10, 15, 20]])

In [81]:
np.hstack([upper,lower])

array([[ 1,  6, 11, 16,  2, 13, 18,  4,  9, 14],
       [ 7, 12, 17,  3,  8, 19,  5, 10, 15, 20]])

In [82]:
np.add(MyArray5,1)

array([[ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20],
       [ 6, 11, 16, 21]])

In [83]:
#36.7ndarray的元素类型

In [84]:
import numpy as np
np.zeros(10,dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [85]:
np.zeros(10,dtype="float")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
a1=np.array([1,2,3,None])
a1

array([1, 2, 3, None], dtype=object)

In [87]:
a1=np.array([1,2,3,None,np.nan])
a1

array([1, 2, 3, None, nan], dtype=object)

In [88]:
#36.8插入与删除

In [89]:
import numpy as np

In [90]:
myArray1=np.array([11,12,13,14,15,16,17,18])
np.delete(myArray1,2)

array([11, 12, 14, 15, 16, 17, 18])

In [92]:
np.insert(myArray1,1,88)

array([11, 88, 12, 13, 14, 15, 16, 17, 18])

In [93]:
#36.9缺失值处理

In [94]:
np.isnan(myArray)

array([False, False, False, False, False, False, False, False, False,
       False])

In [95]:
np.any(np.isnan(myArray))

False

In [96]:
np.all(np.isnan(myArray))

False

In [97]:
MyArray=np.array([1,2,3,np.nan])
np.nansum(MyArray)

6.0

In [98]:
np.sum(MyArray)

nan

In [99]:
#36.10ndarray的广播规则


In [100]:
import numpy as np
A1=np.array(range(1,10)).reshape([3,3])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
A2=np.array([10,10,10])
A2

array([10, 10, 10])

In [102]:
A1+A2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [103]:
A3=np.arange(10).reshape(2,5)
A3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
A4=np.arange(16).reshape(4,4)
A4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
A3+A4

ValueError: operands could not be broadcast together with shapes (2,5) (4,4) 

In [106]:
#36.11 ndarray的排序

In [107]:
import numpy as np
myArray=np.array([11,18,13,12,19,15,14,17,16])
myArray

array([11, 18, 13, 12, 19, 15, 14, 17, 16])

In [108]:
np.sort(myArray)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [109]:
np.argsort(myArray)

array([0, 3, 2, 6, 5, 8, 7, 1, 4], dtype=int64)

In [110]:
MyArray=np.array([[21,22,23,24,25],
                 [35,34,33,32,31],
                 [1,2,3,100,4]])

In [112]:
np.sort(MyArray,axis=1)

array([[ 21,  22,  23,  24,  25],
       [ 31,  32,  33,  34,  35],
       [  1,   2,   3,   4, 100]])

In [113]:
np.sort(MyArray,axis=0)

array([[  1,   2,   3,  24,   4],
       [ 21,  22,  23,  32,  25],
       [ 35,  34,  33, 100,  31]])